using System.Text.Json.Serialization;

namespace PainelFelizCasaNova.Api.Dtos;

public class RegiaoDtoCreate { public string? Nome { get; set; } }
public class RegiaoDtoUpdate { public string? Nome { get; set; } }
public class RegiaoDtoResponse { public int Id { get; set; } public string? Nome { get; set; } public string? Slug { get; set; } }
public class ResumoManualUpdateRequest { public decimal? VgvManual { get; set; } public decimal? VgcManual { get; set; } }
public class VendaCreateRequest { public string? Cliente { get; set; } public string? Numero { get; set; } public int Mes { get; set; } public int Ano { get; set; } public string? Unidade { get; set; } public string? Construtora { get; set; } public bool Assinada { get; set; } public decimal Valor { get; set; } public int RegiaoId { get; set; } public string? Telefone { get; set; } public string? Produto { get; set; } public string? BlocoQuadra { get; set; } public decimal? Percentual { get; set; } public decimal Comissao { get; set; } public string? Corretor { get; set; } public string? Origem { get; set; } public string? Financiado { get; set; } public DateOnly? DataAssinatura { get; set; } public DateOnly? DataEntrada { get; set; } }
public class VendaUpdateRequest { public string? Cliente { get; set; } public string? Numero { get; set; } public int? Mes { get; set; } public int? Ano { get; set; } public string? Unidade { get; set; } public string? Construtora { get; set; } public bool? Assinada { get; set; } public decimal? Valor { get; set; } public int? RegiaoId { get; set; } public string? Telefone { get; set; } public string? Produto { get; set; } public string? BlocoQuadra { get; set; } public decimal? Percentual { get; set; } public decimal? Comissao { get; set; } public string? Corretor { get; set; } public string? Origem { get; set; } public string? Financiado { get; set; } public DateOnly? DataAssinatura { get; set; } public DateOnly? DataEntrada { get; set; } }
public class VendaListResponse { public int Id { get; set; } public string? Cliente { get; set; } public string? Numero { get; set; } public int Mes { get; set; } public int Ano { get; set; } public string? Unidade { get; set; } public string? Construtora { get; set; } public bool Assinada { get; set; } public decimal Valor { get; set; } public string? RegiaoSlug { get; set; } }
public class VendaDetailResponse { public int Id { get; set; } public string? Cliente { get; set; } public string? Numero { get; set; } public int Mes { get; set; } public int Ano { get; set; } public string? Unidade { get; set; } public string? Construtora { get; set; } public bool Assinada { get; set; } public decimal Valor { get; set; } public int RegiaoId { get; set; } public string? Telefone { get; set; } public string? Produto { get; set; } public string? BlocoQuadra { get; set; } public decimal? Percentual { get; set; } public decimal Comissao { get; set; } public string? Corretor { get; set; } public string? Origem { get; set; } public string? Financiado { get; set; } public DateOnly? DataAssinatura { get; set; } public DateOnly? DataEntrada { get; set; } public DateTime CriadoEm { get; set; } public DateTime AtualizadoEm { get; set; } }
public class VendaPerdidaCreateRequest { public string? Cliente { get; set; } public int Mes { get; set; } public int Ano { get; set; } public string? Motivo { get; set; } public int RegiaoId { get; set; } }
public class VendaPerdidaUpdateRequest { public string? Cliente { get; set; } public int? Mes { get; set; } public int? Ano { get; set; } public string? Motivo { get; set; } }
public class VendaPerdidaListResponse { public int Id { get; set; } public string? Cliente { get; set; } public int Mes { get; set; } public int Ano { get; set; } public string? Motivo { get; set; } public string? RegiaoSlug { get; set; } }
public class VendaPerdidaDetailResponse { public int Id { get; set; } public string? Cliente { get; set; } public int Mes { get; set; } public int Ano { get; set; } public string? Motivo { get; set; } public int RegiaoId { get; set; } public DateTime CriadoEm { get; set; } public DateTime AtualizadoEm { get; set; } }
public class UsuarioCreateRequest { public string? Username { get; set; } public string? Email { get; set; } public string? Papel { get; set; } public string? Senha { get; set; } }
public class UsuarioListResponse { public int Id { get; set; } public string? Username { get; set; } public string? Papel { get; set; } public string? Email { get; set; } public DateTime? AtivoAte { get; set; } public DateTime CriadoEm { get; set; } }
public class ImportacaoCsvCreateRequest { public string? Url { get; set; } }
public class ImportacaoCsvResponse { public int Id { get; set; } public string? Status { get; set; } public int VendasProcessadas { get; set; } public int VendasMergidas { get; set; } public int VendasPerdidas { get; set; } public string? ErroMsg { get; set; } public DateTime CriadoEm { get; set; } }
public class OrganizacaoConfigUpdateRequest { public string? LogoBase64 { get; set; } public string? LogoMimeType { get; set; } }
public class OrganizacaoConfigResponse { public string? LogoBase64 { get; set; } public string? LogoMimeType { get; set; } }